#!/usr/bin/python3

import sys

def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            return i, n // i

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        factors = factorize(n)
        print(f"{n}={factors[0]}*{factors[1]}")

if __name__ == "__main__":
    main()

